152 checkin fields
GatherPack/gatherpack pull request #168
Opened 2024-12-19 02:37 UTC by Gerseneck

closes #152

2024-12-21 02:39 UTC, ez500 requested changes

2024-12-21 02:39 UTC, ez500 commented on app/views/checkins/edit.html.erb
>      <h1>Editing <%= @checkin.identifier_name %></h1>
![image](https://github.com/user-attachments/assets/0288758b-3c6f-4470-98d3-fef8d33a9fd5)

2024-12-21 02:39 UTC, ez500 commented on app/views/checkins/show.html.erb
Breadcrumb... also consider doing a "back to event" button

![image](https://github.com/user-attachments/assets/9087930e-39af-45a8-a381-deb814c341d3)

2024-12-21 02:39 UTC, ez500 commented on app/views/checkins/show.html.erb
Also... consider linking "Test Display Name 3" to the actual person profile, or something like that (to connect the person's checkins with the person).

2024-12-21 02:45 UTC, ez500 commented on app/views/checkins/show.html.erb
Sorry I forgot about this... when I change the event type of an event (e.g. from "Test Event Type" to "Competition"), the checkin fields remain the same

![image](https://github.com/user-attachments/assets/fe9497a2-5513-495b-8681-4a4ec08daa40)
![image](https://github.com/user-attachments/assets/774f8566-a7de-4646-9f5a-dddbaf0cb34b)

2024-12-21 02:51 UTC, Gerseneck commented on app/views/checkins/show.html.erb
> Sorry I forgot about this... when I change the event type of an event (e.g. from "Test Event Type" to "Competition"), the checkin fields remain the same. "Rooms" belongs to "Test Event Type", but no checkin fields belong to "Competition".
> 
> ![image](https://private-user-images.githubusercontent.com/46542767/397900220-fe9497a2-5513-495b-8681-4a4ec08daa40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NDk1MjksIm5iZiI6MTczNDc0OTIyOSwicGF0aCI6Ii80NjU0Mjc2Ny8zOTc5MDAyMjAtZmU5NDk3YTItNTUxMy00OTViLTg2ODEtNGE0ZWMwOGRhYTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDAyNDcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MGMxM2U5YjZjMTBiN2Q3YjU1NWI1NGVlYzQxNzgxNGY5ZWU3ODFmZWQ2NzQzMTI4Y2MwOTg5MzQ5ZWMyMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Jq0tETXPYKEEQZqT9D4UcWfVoUOOUNn2VGsNR_FqpFk) ![image](https://private-user-images.githubusercontent.com/46542767/397900267-774f8566-a7de-4646-9f5a-dddbaf0cb34b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NDk1MjksIm5iZiI6MTczNDc0OTIyOSwicGF0aCI6Ii80NjU0Mjc2Ny8zOTc5MDAyNjctNzc0Zjg1NjYtYTdkZS00NjQ2LTlmNWEtZGRkYmFmMGNiMzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDAyNDcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZjQ4NTg1YmU5NGVkNDc5Y2FiMDU3ZWZhODA5YmJkNzEzMTVhODFmOTNkMmUxZDYxZTUwNzhiODkzNmI4MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kAJX2eXD-QBCLREXrqO6Ov_YuSvcwGm-FU8c7S5277o)

This is because the fields already exist and are still associated with the checkin. I don't think it's very efficient to remove all the fields for every single checkin when the event type changes. 

I'll take a look into it though.

2024-12-21 02:56 UTC, ez500 commented on app/views/checkins/show.html.erb
If fields are going to be destroyed when changing event types probably do an "Are you sure..." before validation if that is detected

2024-12-21 19:15 UTC, braddoeswebdev requested changes

2024-12-21 19:15 UTC, braddoeswebdev commented on app/models/checkin_field.rb
> +
I would recommend defining the identifier name as `"#{event_type.name} / #{name}"` or something along those lines to avoid ambiguity...

2024-12-21 19:15 UTC, braddoeswebdev commented on app/models/checkin_field_response.rb
> +      created_by.managed_teams.present?
You're missing a check for admin here

2024-12-24 20:16 UTC, ez500 approved these changes

2024-12-27 18:08 UTC, merged